export const ExceptionType = {
  USERS_READ_NOT_FOUND: { id: 1, message: 'Users not found.' },
  TASKS_READ_NOT_FOUND: { id: 2, message: 'Tasks not found.' },
};

export const SuccessType = {
  USERS_SUCCESS: { id: 1, message: 'Users. Completed successfully.' },
  TASKS_SUCCESS: { id: 2, message: 'Tasks. Completed successfully.' },
};
